spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: baeldung
    password: baeldung
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #TODO Deletes everything when stopped change if needed
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect