spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LectorPortal
    username: baeldung
    password: baeldung
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #TODO Deletes everything when stopped change if needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect