spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LectorPortal
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      #FIXME: Changer back to 'update' when I want to persist data

    #TODO Deletes everything when stopped change if needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
gamesesion:
  url: http://localhost:8090