version: '3.8'
services:

  redis:
    image: redis
    container_name: redis
#    restart: always #wenn docker container failed, wird restartet
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning #save 1 or more writes every 20 seconds to disk
    volumes:
      - redis_data:/data #named volume, speichert Redis-Daten auf dem host system.
#    networks:
#      mynetwork: #backend?
#        aliases:
#          - redis
  db:
    image: postgres
    container_name: postgres
#    restart: always #wenn docker container failed, wird restartet
    environment:
      POSTGRES_USER: myuser           #optional damit auch user+password vorhanden
      POSTGRES_PASSWORD: mypassword   #required
#      POSTGRES_DB: mydatabase         #optional für default database
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
#    networks:
#      mynetwork: #backend?
#        aliases:
#          - postgres

#networks:
#  mynetwork:

volumes:
  redis_data:
    driver: local #the actual storage path is created by docker itself -> to create it on a local file system
  db_data:
    driver: local
