spring:
  session:
    redis:
      namespace: spring:session
    timeout: 12h
  datasource:
    url: jdbc:postgresql://localhost:5432/LectorPortal
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #TODO Deletes everything when stopped change if needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      password:
      port: 6379
      username:
server:
  port: 8090
