spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #TODO Deletes everything when stopped change if needed
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  r2dbc:
    password: test
    url: r2dbc:postgresql://localhost:5432/jwt_security
    username: test

server:
  port: 8090
